title: DunlApp Builders
description: My Dev Blog for Projects
author: Jalen Dunlap
logo: 
github: https://github.com/jalen-dunlap
about: My Dev Blog for Projects

baseurl: "https://jalen-dunlap.github.io"
url: "https://jalen-dunlap.github.io"

allowsearch: false

disqus_shortname: jalendunlap
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
